name: 'Prepare clojure env'
description: 'Prepare clojure enviroment for build'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version-file: '.java-version'
        distribution: 'corretto'

    - name: Set timezone to Europe/Helsinki
      shell: bash
      run: |
        sudo timedatectl set-timezone Europe/Helsinki
        echo "Europe/Helsinki" | sudo tee /etc/timezone

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: 2.11.2

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-