name: 'Prepare clojure env'
description: 'Prepare clojure enviroment for build'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
      with:
        java-version-file: '.java-version'
        distribution: 'corretto'

    - name: Set timezone to Europe/Helsinki
      shell: bash
      run: |
        sudo timedatectl set-timezone Europe/Helsinki
        echo "Europe/Helsinki" | sudo tee /etc/timezone

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
      with:
        lein: 2.11.2

    - name: Cache dependencies
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-